name: sic_game
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  ###
  flutter_bloc: ^9.0.0
  shared_preferences: ^2.3.3
  flutter_svg: ^2.0.16
  intl: ^0.20.1
  connectivity_plus: ^6.1.1
  ###
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/chip/
    - assets/dice/
    - assets/settings/
  fonts:
    - family: w300
      fonts:
        - asset: assets/fonts/Sora-Light.ttf
    - family: w600
      fonts:
        - asset: assets/fonts/Sora-SemiBold.ttf
    - family: w700
      fonts:
        - asset: assets/fonts/Sora-Bold.ttf
